## `list` addition

In [1]:
a = [1, 2, 3]
b = [4, 5, 6]
c = a + b
print('type of a is {0}'.format(type(a)))
print('a = {0}'.format(a))
print('b = {0}'.format(b))
print('a + b = {0}'.format(c))

type of a is <class 'list'>
a = [1, 2, 3]
b = [4, 5, 6]
a + b = [1, 2, 3, 4, 5, 6]


## `numpy` array addition

In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print('type of a is {0}'.format(type(a)))
print('a = {0}'.format(a))
print('b = {0}'.format(b))
print('a + b = {0}'.format(c))

type of a is <class 'numpy.ndarray'>
a = [1 2 3]
b = [4 5 6]
a + b = [5 7 9]


## `numpy` Matrix Transpose

In [3]:
import numpy as np
A = np.matrix('1, 2, 3 ; 4, 5, 6 ; 7, 8, 9')
print('A = \n{0}'.format(A))
print('A^T = \n{0}'.format(A.T))
print('A^T = \n{0}'.format(A.transpose()))

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
A^T = 
[[1 4 7]
 [2 5 8]
 [3 6 9]]
A^T = 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


## `numpy` Matrix-Matrix Addition

In [4]:
import numpy as np
A = np.matrix('1, 2, 3 ; 4, 5, 6 ; 7, 8, 9')
B = np.matrix('10, 12, 13 ; 14, 15, 16 ; 17, 18, 19')
C = A + B
print('A = ')
print(A)
print('B = ')
print(B)
print('A + B = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[10 12 13]
 [14 15 16]
 [17 18 19]]
A + B = 
[[11 14 16]
 [18 20 22]
 [24 26 28]]


## `numpy` Matrix-Matrix Multiplication

In [5]:
import numpy as np
A = np.matrix('1, 2, 3 ; 4, 5, 6 ; 7, 8, 9')
B = np.matrix('10, 12, 13 ; 14, 15, 16 ; 17, 18, 19')
C = A * B
print('A = ')
print(A)
print('B = ')
print(B)
print('A * B = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
B = 
[[10 12 13]
 [14 15 16]
 [17 18 19]]
A * B = 
[[ 89  96 102]
 [212 231 246]
 [335 366 390]]


## `numpy` Matrix-Vector Multiplication

Usage of `np.matrix` type

In [6]:
import numpy as np
A = np.matrix('1, 2, 3 ; 4, 5, 6 ; 7, 8, 9')
b = np.matrix('0 ; 6 ; 9')
C = A * b
print('A = ')
print(A)
print('b = ')
print(B)
print('A * b = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
b = 
[[10 12 13]
 [14 15 16]
 [17 18 19]]
A * b = 
[[ 39]
 [ 84]
 [129]]


Usage of `np.array` type

In [7]:
import numpy as np
A = np.matrix('1, 2, 3 ; 4, 5, 6 ; 7, 8, 9')
b = np.array([0, 6, 9])
C = np.dot(A, b)
print('A = ')
print(A)
print('b = ')
print(B)
print('A * b = ')
print(C)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
b = 
[[10 12 13]
 [14 15 16]
 [17 18 19]]
A * b = 
[[ 39  84 129]]


## `numpy` Linear System Solver

In [8]:
import numpy as np
A = np.matrix('8, 1, 6; 3, 5, 7; 4, 9, 2')
x = np.matrix('0 ; 6 ; 9') # desired solution
b = A * x
print('A = ')
print(A)
print('x = ')
print(x)
print('b = A * x = ')
print(b)

A = 
[[8 1 6]
 [3 5 7]
 [4 9 2]]
x = 
[[0]
 [6]
 [9]]
b = A * x = 
[[60]
 [93]
 [72]]


### Matrix `A` Property

In [9]:
print('determinant of A = ', np.linalg.det(A))
print('condition number of A = ', np.linalg.cond(A))
print('Eigen values and eigen vectors')
eigen_values, eigen_vector = np.linalg.eig(A)
print(eigen_values)
print(eigen_vector)

determinant of A =  -360.0
condition number of A =  4.33012701892
Eigen values and eigen vectors
[ 15.           4.89897949  -4.89897949]
[[-0.57735027 -0.81305253 -0.34164801]
 [-0.57735027  0.47140452 -0.47140452]
 [-0.57735027  0.34164801  0.81305253]]


Usage of `inv` (not recommended)

In [10]:
import numpy as np
A = np.matrix('8, 1, 6; 3, 5, 7; 4, 9, 2')
x = np.matrix('0 ; 6 ; 9') # desired solution
b = A * x
A_inv = np.linalg.inv(A)
x_sol = A_inv * b
print('x = ')
print(x)
print('x_sol = ')
print(x_sol)

x = 
[[0]
 [6]
 [9]]
x_sol = 
[[  2.66453526e-15]
 [  6.00000000e+00]
 [  9.00000000e+00]]


Usage of `solve`

In [11]:
import numpy as np
A = np.matrix('8, 1, 6; 3, 5, 7; 4, 9, 2')
x = np.matrix('0 ; 6 ; 9') # desired solution
b = A * x
x_sol = np.linalg.solve(A, b)
print('x = ')
print(x)
print('x_sol = ')
print(x_sol)

x = 
[[0]
 [6]
 [9]]
x_sol = 
[[ 0.]
 [ 6.]
 [ 9.]]
